######################## default configuration ####################
baseURL = "https://goldenpandacrochet.netlify.app/"
languageCode = "en"
title = "GPC | Golden Panda Crochet"
theme = "hargo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Products"
  URL = "products"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 3

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Products"
  URL = "products"
  weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "FAQ"
  URL = "faq"
  weight = 3

  [[menu.footer]]
  name = "Terms & Conditions"
  URL = "terms-conditions"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "50.29420056062527"
mapLongitude = "18.67055772076395"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "+48 691 762 164"
email = "paulina.zab97@gmail.com"
location = "Gliwice, Poland"
# copyright
copyright = "| Copyright &copy; 2019 [Gethugothemes](https://gethugothemes.com) All Rights Reserved |"
# Snipcart Credentials
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
currencySymbol = "PLN"
#currencySymbol = "$"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "475398"
  publicKey = "657321e16fa1bd47a102c1ec808c4e6d"

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "https://www.facebook.com/profile.php?id=100066893749525"

  [[params.social]]
  icon = "ti-twitter-alt"
  link = "https://twitter.com/crochet_panda"

  [[params.social]]
  icon = "ti-youtube"
  link = "#"

  [[params.social]]
  icon = "ti-instagram"
  link = "https://www.instagram.com/dreaming_of_hollywood/"

  [[params.social]]
  icon = "ti-pinterest"
  link = "https://www.pinterest.com/goldenpandacrochet/"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io
